name: rcmania-turn

services:
  turn:
    profiles: ["turn"]
    image: coturn/coturn:4.6.3-r4-alpine
    restart: unless-stopped
    network_mode: host
    command: ["-c", "/etc/coturn/turnserver.conf"]
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
