logLevel: info
rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889

pathDefaults:
  source: publisher
  record: yes
  recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordSegmentDuration: 10m
  recordDeleteAfter: 30m

paths:
  camera-1:
  camera-2:
  onboard-1:
  public:
